series: Basic C++
title: Flow Control
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: The basic tools used to write real programs.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Functions